name: "Push Docker Image"

on:
  push:
    tags:
      - "v*"

env:
  TARGET_PLATFORMS: linux/amd64,linux/arm64/v8,linux/arm/v7

  GHCR_URL: ghcr.io
  GHCR_LIBRARY: jessenich
  GHCR_REPO: ubuntu
  DOCKERHUB_LIBRARY: jessenich91
  DOCKERHUB_REPO: ubuntu
  LABELS: |
    maintainer=Jesse N. <jesse@keplerdev.com>
    org.opencontainers.image.source=https://github.com/jessenich/docker-ubuntu/

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: [ server ]
        variant: [ 20.04, 18.04, 16.04 ]

    name: "Build Ubuntu Variant: ${{ matrix.variant }}"

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
            version: latest
            install: true
            driver-opts: image=moby/buildkit:master
            use: true

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ${{ env.GHCR_URL }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          github-token:  ${{ secrets.GITHUB_TOKEN }}
          labels: ${{ env.LABELS }}
          images: |
            "docker.io/${{ env.DOCKERHUB_LIBRARY }}/${{ env.DOCKERHUB_REPO }}"
            "ghcr.io/${{ env.GHCR_LIBRARY }}/${{ env.GHCR_REPO }}"
          tags: |
            type=raw,enable=${{ matrix.variant == '20.04' }},priority=100,value=${{ matrix.tag }}
            type=semver,enable=true,priority=300,pattern={{major}}.{{minor}}.{{patch}},suffix=-${{ matrix.variant }}.${{ matrix.tag }}
          flavor: latest=false

      - name: Build & Push Latest
        uses: docker/build-push-action@v2
        with:
          context: ./docker/images/server
          file: ./docker/images/server/Dockerfile
          labels: ${{ steps.meta.output.labels }}
          build-args: VARIANT=${{ matrix.variant }}
          platforms: ${{ env.TARGET_PLATFORMS }}
          pull: true
          push: true
          tags: ${{ steps.meta.outputs.tags }}
